# Generated by Django 5.0.6 on 2024-05-22 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=200)),
                ('cargo', models.CharField(max_length=100)),
                ('email_corporativo', models.EmailField(max_length=254)),
                ('departamento', models.CharField(max_length=100)),
                ('data_admissao', models.DateField()),
            ],
        ),
    ]
